version: '3'

services:
  server:
    environment:
      - FLASK_APP=app:app
      - FLASK_DEBUG=1
      - DEBUG=1
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
    build: .
    image: ivkin/golf
    container_name: golf-server
    ports:
      - "80:5001"
    command: flask run
    stdin_open: true
    tty: true